### PR TITLE
Fix typo in setup.py / more constexpr / bump coding conventions

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by pramodk** [comment]
It's draft but LGTM

**Comment by pramodk** [comment]
@tristan0x : this is in draft for quite some time. You want to work on this more or want to get this sooner to avoid more conflicts?

**Comment by tristan0x** [comment]
Yeah I will make some progress on this one soon

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
