### PR TITLE
Directly construct *Visitors instead of constructing and assigning #171

### PR DESCRIPTION
**Pull request by cattabiani**
- i.e.: "auto lv = AstLookupVisitor(bla bla)" ->
        "AstLookupVisitor lv(bla bla)"
- "make clang-format cmake-format" slightly changed 2 more files

### CODE REVIEW

**Comment by cattabiani** [comment]
sorry, I thought the change was very minor and there were no problems. I'll check on monday

**Comment by cattabiani** [comment]
please retest

**Comment by cattabiani** [comment]
pretty please retest

**Comment by pramodk** [comment]
By the way, in commit messages you can add "fixes #issue_numer" to automatically close the issue on merge.  (see [here](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)).

**Pull request merged**
