### PR TITLE
Bugfix: CONSERVE statement OUTSIDE of a KINETIC block -> seg. fault

### PR DESCRIPTION
**Pull request by cattabiani**
Related to [issue 280](https://github.com/BlueBrain/nmodl/issues/280)

Solution: added a flag in the KineticBlockVisitor that inhibit
visit_* functions in case we are not visiting a kinetic block.

### CODE REVIEW

**Comment by cattabiani** [comment]
Please retest

**Comment by pramodk** [comment]
@cattabiani : I merge lastest master as fmt link related issue was fixed in Omar's PR.

**Comment by cattabiani** [comment]
yes, the plan is to remove the conserve from the derivative block. However, if there is, a conserve statement outside the kinetic this generates a seg. fault. The issue is somewhat orthogonal to what you are saying

**Comment by nrnhines** [comment]
In NEURON the CONSERVE keyword is only allowed in a KINETIC block. Same with COMPARTMENT and LONGITUDINAL_DIFFUSION.

**Comment by cattabiani** [comment]
A different [branch](https://github.com/BlueBrain/nmodl/pull/285) takes care of this bug in a more organic way. Thus, this branch was dropped.

**Pull request closed without merging**
