### PR TITLE
Support for Random number generator as language construct

### PR DESCRIPTION
**Pull request by ohm314**
As described in #383 this PR introduces a native random type into NMODL based on the `random123` implementation. Having support from random numbers in the language will allow us to drop a lot of `VERBATIM` code and unifies semantics and implementation of random numbers in CoreNEURON (and NEURON) mechanisms.

## Status

- [x] Tests for parsing
- [ ] Tests for code generation
- [x] AST definition in modl
- [x] Bison production rules
- [x] semantic validation pass
- [x] supporting data structures for code generation
- [ ] C++ code generation

## How to test

Look at the unit tests in `test/unit/parser.cpp`.

### CODE REVIEW

**Comment by pramodk** [comment]
@ohm314: Is there any other items you have locally? Or, this is ready to discuss with @alkino?

**Comment by ohm314** [comment]
No local items - I will continue work here in a couple weeks but alternatively we can discuss with @alkino sooner. Did you have a chance to look at the PR in its current state? macos tests failed because of some homebrew issue.

**Comment by ohm314** [comment]
The last thing I was doing, was looking into netstim to understand a little better code generation and what can be factored out. I wanted to continue with this task once I finish up a few other items that were waiting for a long time.

**Comment by pramodk** [comment]
Ok, yes! we wanted to have hand-written netstim cpp code before changing code generation pass!

**Comment by 1uc** [comment]
Implemented via a different PR.

**Pull request closed without merging**
