### PR TITLE
Deduplicate renaming of state vars

### LINKED ISSUE #1395: Deduplicate printing STATE initial values.
STATE variable require are initialized from `0`-suffixed global variables, i.e. `X` from `X0`. NMODL contains the logic once for CoreNEURON and once for NEURON.

The task would be to extract the code that does:
```c++
printer->fmt_line("{} = {};", get_variable_name("X"), get_variable_name("X0"));
```
Then lift it to `CodegenCppVisitor` and use it in both `Codegen{Coreneuron,Neuron}Visitor`.

### PR DESCRIPTION
**Pull request by alkino**
Shoud close #1395

### CODE REVIEW

**Comment by 1uc** [comment]
Here's the changes:
https://github.com/BlueBrain/nmodl-references/commit/4bb98734b97101d4e66559094d5d718c4d02ab37

Please double-check which if you prefer one variation over the other or if they're equal.

**Review by 1uc — APPROVED** [review]
Nice, one more thing tidied up :)

**Comment by alkino** [comment]
> Here's the changes: [BlueBrain/nmodl-references@4bb9873](https://github.com/BlueBrain/nmodl-references/commit/4bb98734b97101d4e66559094d5d718c4d02ab37)
> 
> Please double-check which if you prefer one variation over the other or if they're equal.

What do you think?
I choose this one to avoid creating a local variable `_i`...

**Comment by 1uc** [comment]
I'm coming around to the NOCMODL way of reserving all `_` prefixed names; but either is fine.

**Pull request merged**
