### PR TITLE
Fix missing null-terminator.

### PR DESCRIPTION
**Pull request by 1uc**

### CODE REVIEW

**Comment by 1uc** [comment]
Would have been detectable with ASAN enabled version of NRN.

**Review by JCGoran — COMMENTED** [review]
This fixes a memory leak? If so, what's a MWE that would demonstrate the problem?

**Comment by 1uc** [comment]
> This fixes a memory leak? If so, what's a MWE that would demonstrate the problem?

No, it fixes an out-of-bounds access. It's covered many times already; but without an NRN with ASAN enabled (or similar) there's no guarantee that it results in a failure (e.g. SEGFAULT).

**Review by JCGoran — APPROVED** [review]
LGTM then!

**Pull request merged**
