### PR TITLE
Run SonarSource on demand.

### PR DESCRIPTION
**Pull request by 1uc**

### CODE REVIEW

**Comment by 1uc** [comment]
Shaves off 2 minutes of build time.

**Review by pramodk — COMMENTED** [review]
LGTM. Mentioning this in `CONTRIBUTING.rst` might be helpful?

**Comment by 1uc** [comment]
BTW, it's now faster than the Windows build; and about as fast as the documentation CI. Might be worth just running it to ensure it doesn't rot away.

**Comment by 1uc** [comment]
Let's leave it in place for now. When it's the last thing to go green, we can turn it off.

**Pull request closed without merging**
