### PR TITLE
Log a critical instead of an assert if we cannot find the block to so…

### PR DESCRIPTION
**Pull request by alkino**
…lved

Otherwise it only segmentation fault in Release

### CODE REVIEW

**Comment by alkino** [comment]
I'm not sure what we should do, how can we end the program there?
Is `exit(1)` good?

**Comment by iomaganaris** [comment]
I was thinking that maybe based on [Exceptions versus assertions
](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=msvc-170#exceptions_versus_assertions) an assertion fits here?

**Comment by useranonym** [comment]
> I was thinking that maybe based on [Exceptions versus assertions](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=msvc-170#exceptions_versus_assertions) an assertion fits here?

that's true but `assert` is removed in non-debug builds and hence the problem?

**Comment by alkino** [comment]
@iomaganaris the problem of assert is that it is not executed with Release build. As this assertion is about conformance of mod files, it needs to be run all the time, as we cannot more trust the user input in Release that in Debug. I was running nmodl and i got a segfault without explanation on a buggy modfile.

**Review by pramodk — APPROVED** [review]

**Pull request merged**
