### PR TITLE
Apply user_functions to vecFcode too

### PR DESCRIPTION
**Pull request by alkino**
When functions inside solve block are not inlined sympy cannot find them. The problem is already fixed for vecJcode, do the same.

Related to #927

### CODE REVIEW

**Comment by cattabiani** [comment]
may you add a CI test that crashes with the previous version? It should be simple: with sympy 1.9 `beta(x)` was transformed to `beta(x,x)`. This probably cannot compile.

**Comment by alkino** [comment]
This patch is not fixing this bug. But the bug that not inlined functions are not found.

**Comment by cattabiani** [comment]
ok, it was another bug. I sincerly do not know how this impacts nmodl. I do not know what it should do. I think you need someone else for the review

**Comment by alkino** [comment]
Without the patch, the following file fail
```
NEURON {
    SUFFIX glia
}

STATE {
    C1
    C2
}

BREAKPOINT {
    SOLVE kstates METHOD sparse
}

FUNCTION alfa(v(mV)) {
    alfa = exp(v)
}

FUNCTION tau(v(mV)) {
    tau = exp(-v)
}

KINETIC kstates {
    ~ C1 <-> C2 (alfa(v), tau(v))
}
```

Because functions `alfa` and `tau` are not known, so sympy return
```
vecFcode=['F[0] = /* Not supported in C: */
/* alfa */
/* tau */
-X[0]*dt*alfa(v) - X[0] + X[1]*dt*pow(tgamma(v), 2)/tgamma(2*v) + old_C1',
'F[1] = /* Not supported in C: */
/* alfa */
/* tau */
X[0]*dt*alfa(v) - X[1]*dt*pow(tgamma(v), 2)/tgamma(2*v) - X[1] + old_C2']
```

And our internal parser don't know C comments

**Comment by cattabiani** [comment]
it looks like it actually solved the problem. Are you sure to the left you do not have `F[0]` and `F[1]` and somewhere someone leaves the `'`?

**Comment by pramodk** [comment]
> it looks like it actually solved the problem.

That's my understanding as well. By providing `user_functions`, sympy no loner produce C comments and avoids errors in NMODL parser.

@alkino : snout the failing mod file we had - maybe we can add that as a unit test? (in the unit test, we will not run Inline visitor and then it should cover the use case)

**Review by pramodk — APPROVED** [review]
we can merge #937 to this branch first?

**Comment by alkino** [comment]
Those are 2 differents issues

**Review by iomaganaris — APPROVED** [review]
LGTM

**Pull request merged**
