### PR TITLE
Bump CMake min version to 3.15

### PR DESCRIPTION
**Pull request by alexsavulescu**

### CODE REVIEW

**Review by alkino — APPROVED** [review]

**Comment by alkino** [comment]
Maybe in a next PR, we should use Python3 instead of deprecated [PythonInterp](https://cmake.org/cmake/help/latest/module/FindPython3.html).

**Comment by alexsavulescu** [comment]
Will update nmodl Docker image to `manylinux2014` before.

**Comment by alexsavulescu** [comment]
wheel update here: https://github.com/BlueBrain/nmodl/pull/719

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
