### PR TITLE
Bump pybind11 to v2.6.1

### PR DESCRIPTION
**Pull request by alkino**
update pybind11 to better support python 3.9

### CODE REVIEW

**Comment by alkino** [comment]
Please retest

**Comment by pramodk** [comment]
Curious - is there specific in pybind v2.6.1 ?

**Comment by alkino** [comment]
It does not seem, it's only that flex is installed, after that azure try to launch `brew clean` it fails and `bison` is never installed.

**Comment by alkino** [comment]
pybind11 > 3.5.0 ask for a cmake >= 3.4, and we wish to stay with cmake 3.3 as long as necessary.

**Pull request closed without merging**
