### PR TITLE
Put nrnunits.lib into share/nmodl instead of share

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by cattabiani** [comment]
just a question: why?

**Comment by alkino** [comment]
> just a question: why?

Currently 3 differents people try to install differents `nrnunits.lib` files: neuronsimulator/nrn, BlueBrain/nmodl and BlueBrain/mod2c

Because they are different we want to have three in the same time.
`share/nrnunits.lib` is for neuronsimulator/nrn
`share/mod2c/nrnunits.lib` for BlueBrain/mod2c
`share/nmodl/nrnunits.lib` for BlueBrain/nmodl

**Comment by alkino** [comment]
I checked that it works well with Coreneuron, but in fact nmodl don't use the env var for finding nrnunits.lib, it's hardcoded inside the binary

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
