### PR TITLE
Provide both end() iterators to std::mismatch to prevent seeking beyond the end of std::string

### PR DESCRIPTION
**Pull request by matz-e**
Became apparent with MSVC, which in this case crashes hard comparing `it.first = "yotta"` and `denomitator_name = "sec2"`.

### CODE REVIEW

**Comment by 1uc** [comment]
How did you find this? With the immediate following are we missing test coverage?

**Comment by matz-e** [comment]
> How did you find this? With the immediate following are we missing test coverage?

MSVC's debug build has very aggressive asserts in the STL. Building with MSVC will provide adequate coverage? Maybe GCC/Clang have other guards for this.

**Comment by 1uc** [comment]
It reads like it's a proper bug. On that should result in an ASAN failure. If true, why do we need MSVC to find the bug? Are we not running ASAN during CI? Or are we missing a test that exposes the problem? Again, it would be helpful to know what exactly failed.

**Comment by matz-e** [comment]
I think there are flags in the glibc that would trigger similar asserts.

**Comment by 1uc** [comment]
Very good!

**Review by 1uc — APPROVED** [review]

**Pull request merged**
